services:
  api:
    build: .
    container_name: devops-api
    ports:
      - "8000:8000"

  nginx:
    build: ./nginx
    container_name: devops-nginx
    ports:
      - "80:80"
    depends_on:
      - api

  prometheus:
    build: ./prometheus
    container_name: devops-prometheus
    ports:
      - "9090:9090"
    depends_on:
      - api

  grafana:
    image: grafana/grafana:latest
    container_name: devops-grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana

  jenkins:
    build: ./jenkins
    container_name: devops-jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

volumes:
  jenkins_home:
  grafana_data: